name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKER_PLATFORMS: linux/amd64,linux/arm64
  DOCKER_IMAGE_NAME: nxs-data-anonymizer
  DOCKER_IMAGE_TAG: 1.14.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            VERSION=${{ env.DOCKER_IMAGE_TAG }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
